### PR TITLE
[TEST] org map circular fix

### PR DESCRIPTION
**Pull request by bumblebee89**

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by bumblebee89** [comment]
@lukaszgryglicki fix for single circular org in previous PR.

**Comment by bumblebee89** [comment]
@lukaszgryglicki merged

**Comment by lukaszgryglicki** [comment]
Fix works:
1st run:
```
{"text":"Added organization 'Power Home Remodeling Group' (id=77299), Organizations: added:1 renamed:0 deleted:0 skipped:0, Enrollments: conflicts:0 archive conflicts:0 updated:0"}
```
2nd run:
```
{"text":"Nothing to update"}
```

**Pull request merged**
