### PR TITLE
[PROD] update org-map

### PR DESCRIPTION
**Pull request by bumblebee89**
same update as in test [here](https://github.com/LF-Engineering/dev-analytics-affiliation/pull/97)

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by bumblebee89** [comment]
@lukaszgryglicki merged

**Comment by lukaszgryglicki** [comment]
1st run:
```
{"text":"Deleted organization 'CP Cranes' (id=75893), Deleted organization 'huge domains' (id=75895), Deleted organization 'HPE' (id=75894), Deleted organization 'Networking' (id=75896), Deleted organization 'SONY' (id=75897), Deleted organization 'Univa' (id=75898), Deleted organization 'WW' (id=75899), Deleted organization 'Zink Media LLC' (id=75900), Organizations: added:0 renamed:0 deleted:8 skipped:0, Enrollments: conflicts:0 archive conflicts:0 updated:0"}
```
2nd run:
```
{"text":"Nothing to update"}
```

**Comment by bumblebee89** [comment]
thanks @lukaszgryglicki

**Pull request merged**
