### PR TITLE
[PROD] DA-2097- Add issues_assigned and issues_closed for bugzilla top contributors

### PR DESCRIPTION
**Pull request by teragopher**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
It "lgtm" at the first glance, but please let me run that locally tomorrow, to make sure all cases are handled, especially: normal and CSV output.

**Comment by lukaszgryglicki** [comment]
Needed to add ff9b13cb77b0db8222196eebaa9e67ec4e22abb3 code,m but even after that I'm getting `Found 1 problem(s)\\nline 1:335: Unknown column [is_open]` for `yocto`, `bugzilla`.

**Comment by lukaszgryglicki** [comment]
Works for dpdk, so it means this supports `bugzillarest` (used by DPDK) but not `bugzilla` (used by Yocto), probably `is_open` is named differently there, checking this.

**Comment by lukaszgryglicki** [comment]
Fixed, so for `bugzilla` I'm using `status` column for counting `bugzilla_closed`:
- column: `bugzilla_issues_closed":   "count(status) as bugzilla_issues_closed`.
- condition: ` and \"url\" is not null and \"status\" in ('CLOSED', 'RESOLVED')`.
See 2e3baf6f5e81050952587b9a306788598656be94
Test locally:
- `./sh/curl_get_top_contributors.sh data-plane-development-kit/dpdk 0 2552790984700 1 0 '' bugzilla_issues_closed desc | jq`.
- `./sh/curl_get_top_contributors_csv.sh data-plane-development-kit/dpdk 0 2552790984700 1 0 '' bugzilla_issues_closed desc`.
- `./sh/curl_get_top_contributors.sh yocto 0 2552790984700 1 0 '' bugzilla_issues_closed desc | jq`.
- `./sh/curl_get_top_contributors_csv.sh yocto 0 2552790984700 1 0 '' bugzilla_issues_closed desc`.
Deployed.
cc @1010sachin @teragopher .

**Comment by teragopher** [comment]
@lukaszgryglicki Thanks 👍

**Pull request merged**
