### PR TITLE
[TEST] update org map

### PR DESCRIPTION
**Pull request by bumblebee89**

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by bumblebee89** [comment]
@lukaszgryglicki merged

**Comment by lukaszgryglicki** [comment]
1st run:
```
{"text":"Added organization 'Kabbage' (id=78077), Updated organization 'American Express Kabbage Inc.' -> 'Kabbage' on 4 enrollments, Updated organization 'American Express Kabbage Inc.' -> 'Kabbage' on 9 archived enrollments, Deleted organization 'American Express Kabbage Inc.' (id=75519), Updated organization 'BMW Car IT GmbH' -> 'BMW' on 16 enrollments, Updated organization 'BMW Car IT GmbH' -> 'BMW' on 5 archived enrollments, Deleted organization 'BMW Car IT GmbH' (id=74048), Added organization 'Cloudsmith Ltd' (id=78078), Deleted organization 'Cloudsmith' (id=59101), Added organization 'ControlPlane.io' (id=78079), Updated organization 'ControlPlane' -> 'ControlPlane.io' on 21 enrollments, Updated organization 'ControlPlane' -> 'ControlPlane.io' on 167 archived enrollments, Deleted organization 'ControlPlane' (id=52164), Added organization 'Decipher Technology Studios' (id=78080), Updated organization 'Grey Matter' -> 'Decipher Technology Studios' on 26 enrollments, Updated organization 'Grey Matter' -> 'Decipher Technology Studios' on 6 archived enrollments, Deleted organization 'Grey Matter' (id=52507), Updated organization 'Dell Technologies, Inc.' -> 'Dell Technologies' on 2 enrollments, Deleted organization 'Dell Technologies, Inc.' (id=76749), Updated organization 'Exanet' -> 'Dell Technologies' on 5 enrollments, Deleted organization 'Exanet' (id=36942), Added organization 'Devgistics, LLC' (id=78081), Updated organization 'InfoSiftr, LLC' -> 'Devgistics, LLC' on 23 enrollments, Updated organization 'InfoSiftr, LLC' -> 'Devgistics, LLC' on 42 archived enrollments, Deleted organization 'InfoSiftr, LLC' (id=56946), Deleted organization 'Face++|??' (id=54078), Added organization 'Flex LTD' (id=78082), Updated organization 'Flex LTD (Formerly Flextronics)' -> 'Flex LTD' on 41 enrollments, Updated organization 'Flex LTD (Formerly Flextronics)' -> 'Flex LTD' on 16 archived enrollments, Deleted organization 'Flex LTD (Formerly Flextronics)' (id=40855), Added organization 'Institute of Graduate Studies and Research (IGSR)' (id=78083), Updated organization 'IGSR' -> 'Institute of Graduate Studies and Research (IGSR)' on 1 enrollments, Deleted organization 'IGSR' (id=70388), Added organization 'ITOCHU Techno-Solutions (CTC) America, Inc.' (id=78084), Updated organization 'Itochu Techno Solutions America Inc.' -> 'ITOCHU Techno-Solutions (CTC) America, Inc.' on 1 enrollments, Updated organization 'Itochu Techno Solutions America Inc.' -> 'ITOCHU Techno-Solutions (CTC) America, Inc.' on 4 archived enrollments, Deleted organization 'Itochu Techno Solutions America Inc.' (id=70054), Added organization 'Kubermatic GmbH' (id=78085), Updated organization 'Kubermatic GmbH (f/k/a Loodse)' -> 'Kubermatic GmbH' on 287 enrollments, Updated organization 'Kubermatic GmbH (f/k/a Loodse)' -> 'Kubermatic GmbH' on 526 archived enrollments, Deleted organization 'Kubermatic GmbH (f/k/a Loodse)' (id=75062), Deleted organization 'Nagra Kudelski Group (OpenTV)' (id=75383), Updated organization 'Massachusetts Institute of Technology (MIT)' -> 'Massachusetts Institute of Technology' on 28 enrollments, Updated organization 'Massachusetts Institute of Technology (MIT)' -> 'Massachusetts Institute of Technology' on 9 archived enrollments, Deleted organization 'Massachusetts Institute of Technology (MIT)' (id=52719), Added organization 'PrimaryIO, Inc.' (id=78086), Updated organization 'CacheBox' -> 'PrimaryIO, Inc.' on 3 enrollments, Updated organization 'CacheBox' -> 'PrimaryIO, Inc.' on 1 archived enrollments, Deleted organization 'CacheBox' (id=34624), Added organization 'Siemens AG' (id=78087), Updated organization 'Siemens Schweiz AG' -> 'Siemens AG' on 467 enrollments, Updated organization 'Siemens Schweiz AG' -> 'Siemens AG' on 686 archived enrollments, Deleted organization 'Siemens Schweiz AG' (id=73920), Added organization 'Texas State University' (id=78088), Updated organization 'Texas State University-San Marcos' -> 'Texas State University' on 2 enrollments, Updated organization 'Texas State University-San Marcos' -> 'Texas State University' on 1 archived enrollments, Deleted organization 'Texas State University-San Marcos' (id=57368), Updated organization 'TÜBİTAK' -> 'TUBITAK UEKAE' on 8 enrollments, Updated organization 'TÜBİTAK' -> 'TUBITAK UEKAE' on 26 archived enrollments, Deleted organization 'TÜBİTAK' (id=54745), Updated organization 'Vodafone' -> 'Vodafone Group Plc.' on 32 enrollments, Updated organization 'Vodafone' -> 'Vodafone Group Plc.' on 105 archived enrollments, Deleted organization 'Vodafone' (id=58752), Updated organization 'Vodafone Idea Limited' -> 'Vodafone Group Plc.' on 3 enrollments, Deleted organization 'Vodafone Idea Limited' (id=59714), Organizations: added:12 renamed:0 deleted:21 skipped:0, Enrollments: conflicts:0 archive conflicts:0 updated:2573"}
```
2nd run:
```
{"text":"Nothing to update"}
```
So we're all set.
cc @bumblebee89

**Comment by bumblebee89** [comment]
@lukaszgryglicki  awesome. Will do same for prod. Thanks

**Pull request merged**
