### PR TITLE
DA-4235 [test]: merge solace systems into Solace org

### PR DESCRIPTION
**Pull request by aultron**

### CODE REVIEW

**Review by bumblebee89 — APPROVED** [review]
/lgtm

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
I'll do one update regarding `-MISSING-NAME` and then I'll run it and let u know the results.

**Comment by lukaszgryglicki** [comment]
1st run:
```
{"text":"Updated organization 'Solace Systems' -> 'Solace' on 3 enrollments, Updated organization 'Solace Systems' -> 'Solace' on 1 archived enrollments, Deleted organization 'Solace Systems' (id=69154), Organizations: added:0 renamed:0 deleted:1 skipped:0, Enrollments: conflicts:0 archive conflicts:0 updated:4"}
```

2nd run:
```
{"text":"Nothing to update"}
```
So we're OK.

**Pull request merged**
