### PR TITLE
fix org map indentation

### PR DESCRIPTION
**Pull request by teragopher**

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
There is also at least one more error in this mapping, see my comment on the previous PR. Thanks

**Comment by lukaszgryglicki** [comment]
@teragopher please address [this](https://github.com/LF-Engineering/dev-analytics-affiliation/pull/27#issuecomment-728106223) before I merge this. Possibly try to find similar issues (if there are any other) - I don't know why GitHub UI shows so many changes that this is almost on-reviewable.

**Comment by teragopher** [comment]
@lukaszgryglicki thanks, I am working on this, will push an update soon

**Comment by lukaszgryglicki** [comment]
Great, so I'll merge and give you an update tomorrow - first thing.

**Comment by teragopher** [comment]
Awesome, thanks

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm and will see after the merge

**Pull request merged**
