### PR TITLE
[TEST] update org mapping

### PR DESCRIPTION
**Pull request by bumblebee89**

### CODE REVIEW

**Comment by bumblebee89** [comment]
@lukaszgryglicki please merge if ok and run org map when you have some time. This PR fixes the circular updates from the last PR

**Comment by bumblebee89** [comment]
@lukaszgryglicki merged

**Comment by lukaszgryglicki** [comment]
Looks like this fixed all the issues, see the 2nd run output:

`curl -i -s -H Authorization: Bearer (...) -XPUT https://affiliations.insights.test.platform.linuxfoundation.org/v1/affiliation/map_org_names`:
```
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 02 Jun 2021 11:24:46 GMT
Vary: Origin
X-Request-Id: 009c9296-c395-11eb-8e09-3ef48defadcc
Content-Length: 29
Connection: keep-alive

{"text":"Nothing to update"}
```

**Comment by bumblebee89** [comment]
@lukaszgryglicki awesome, thanks!!

**Pull request merged**
