### PR TITLE
[PROD] DA-2149 Rearrange data source output for top contributors

### PR DESCRIPTION
**Pull request by teragopher**
@lukaszgryglicki please check out `EnrichContributors` method in the SH service file. I had to comment out 2 lines like this `uuids = append(uuids, projectSlug)` because it was causing the query to fail by adding the project slug to the query arguments.

`
{"level":"warning","msg":"[1:2bc2c020e49b3e6f3d852a2da4dc3594259e5044 2:083aacbaa92a194abf871e11474e5502d6547deb 3:e8c7351c0c434496680117029e59324397a91086 4:947df23087e41cc249b565cf21ff1e8947530904 5:806c186f62c88b4c1cb7638fa2b797428459cd19 6:4afcd6a74c4c03859bb922630c16b93d92141795 7:b84eacefe88202f41d15641f3f549ca8d9f33b6a 8:00e56c226e2b276158873aa2920ba94f19a032c7 9:1d212a13cada8b3d361a422bfb949ec2abb5f9b1 10:693d5b10e08a36cf3d519e6c490b9504a301122a 11:27364b10828a0596f529880000a6b5d333b8cbed 12:9177fc92483ef2f3431e29e17cadfa03cb3bc3ed 13:189ad92bc0c7aa98e9313d925b9d50923759a7ea 14:4146cc8a3de8b21f24e6fcab447390f6d6ca9a4c 15:b3bf7d18d2f23ad80e300a7978b3d7471f8fad56 16:a7e3a754422ba7bfc2aae9fd8dd44f862821da23 17:00fd9b5266618b340a3d8e29be019075d467614c 18:10d14356012ed66a6a355539d41dc9835ac04124 19:d840f02de2bd9ef10adf3374302a367bea03842a 20:e0e61e7cb10dcb21f706f9e5d45f6f2df9b5283a 21:27335f0cce961bd17fe1efc02d9d3bdd77598fa9 22:5a9fac0bc5ac67c9a3ca1be481ac39f2c6c88e7b 23:08f366b86073d724b7ea62b2bec8053e4d44ba3b 24:4bc357ab28c45715c36ebb905c723b8f082df77f 25:5b3cc4d3a9c7b9a26b3eeb49b0cb36ec8de23285 26:16de9de94d93ff087960a7aa5471f120dcdc14ee 27:31c04277290bc20a24312df912381aea606d0576 28:54aa90527bd155b41e90b54bca37cc79bda0c0fc 29:54e43555b2c3107b9696d7ae205947786647d95b 30:7e13cb52b44c6697c6becb09226cc45284f0a83c 31:903b4dc131f418911712452cc6a34bdae77c0ec3 32:c2181c0b54907dc6fabd291919e863d8499a5fe6 33:060e9d5737ffab0af4ea0ecf50c19851fe89a1b6 34:16a1fd9fde6841a05abc8d45b0bd85615ddd453b 35:0ad487c762ac3f76556f9ca3ccd7762d2be44967 36:11f827be6315522221c913dda1e0604d2178f87e 37:1260f27bdfc23cce2ff0e898e0496e2d9f051c53 38:1556cbc6589db937224848245cf807740ead967d 39:163da5301ae2042517383a656be88fd4520ea2fa 40:2636481c7dafff439f989c0b7fa6bef251f0e09a 41:28d58f93469f29f27890102acedaa992b0164f43 42:2da889ecb57d374f139ac9b4f5a7302f032bc2f9 43:2ee15304fe7513e4f617a3d3640a3cfc88a57dc8 44:7e1cd3170bd21a54b374fb65425fd60e71a4a472 45:8f3496dec0c175488d5577c2514806ef93bdfda5 46:9026c000ca607fda86115901a2fde8d45bb1d980 47:9e4ea0c0e9dd3e005f302eedbb1cede8c702be35 48:a9d5212d7751476002baeb12b9504910118ed081 49:aecd19c1cc16cfd77e67ae46df431e7648ee579f 50:b7aab9130a21ae9295ac0a0bb3c2de268151f07c 51:d2b7b45a6316eb53c2fe0c31dca3ac9f39e6919b 52:de20b592a736eb105727de7fd37158ed2ab58d16 53:project1 ]","time":"2020-06-08T21:30:37Z"}
`

`{"level":"info","msg":"GetTopContributors(exit): from:1583877082747 to:1591653082747 limit:1000 offset:0 search: sortField: sortOrder: apiName:GetTopContributors project:project1 username:michael.bammeke topContributors:52 public:true err:GetTopContributors: QueryDB: sql: expected 52 arguments, got 53","time":"2020-06-08T21:51:27Z"}`

### CODE REVIEW

**Comment by lukaszgryglicki** [comment]
This (adding projectSlug) should not be deployed yet? Even the docker image for projectSlug wasn't deployed yet. This is to be tested today before I decide to debug this.

**Comment by lukaszgryglicki** [comment]
Anyway, I'll deal with this while testing projectSlug support.

**Comment by teragopher** [comment]
Thanks @lukaszgryglicki

**Comment by lukaszgryglicki** [comment]
This is fixed, it was just a bug - positional query parameters were `'?'` instead of `?` as they should be.

**Pull request merged**
