### PR TITLE
(test) DA-4013: Update list org api to first lookup and then search org name

### PR DESCRIPTION
**Pull request by ajinkyan83**
Implementing Hybrid solution as suggested by @1010sachin here -
https://jira.linuxfoundation.org/browse/DA-4013?focusedCommentId=532141&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-532141

Verified and tested locally.

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by ajinkyan83** [comment]
Merged test first.

**Comment by lukaszgryglicki** [comment]
Deployed on test.

**Comment by ajinkyan83** [comment]
Thank you @lukaszgryglicki

**Pull request merged**
