### PR TITLE
[prod] DA-3488: PostAddIdentity bug

### PR DESCRIPTION
**Pull request by code-sleuth**
see [#52](https://github.com/LF-Engineering/dev-analytics-affiliation/pull/52)

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
I wonder why we don't remove those `go.mod` and `go.sum` files - every tie anybody else is doing a PR those files change a lot and running make locally changes them again & again, so PRs contain a lot of changes to those files which means nothing. All auto-generated files should be .gitignored IMHO. cc @fayazg @1010sachin

**Comment by code-sleuth** [comment]
Keeping the `go.mod` helps especially in  versioning of our shared library. A new change in the library might require so many changes across a given repo so keeping a specific version while steadily migrating is a major +.

**Comment by lukaszgryglicki** [comment]
Ok, but every time I generate a new image, those two files change, so I basically must commit them again and again or always `git reset --hard`.

**Pull request merged**
