### PR TITLE
clean up map orgs

### PR DESCRIPTION
**Pull request by teragopher**

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
@teragopher ping - approved, but I should not merge. Please merge if this is ready and I'll deploy tomorrow.

**Comment by teragopher** [comment]
@lukaszgryglicki merged... Thanks!!!

**Comment by lukaszgryglicki** [comment]
Thanks!

**Comment by lukaszgryglicki** [comment]
Deployed.

**Pull request merged**
