### PR TITLE
DA-3055: Add Gerrit review metrics for Top contributors API

### PR DESCRIPTION
**Pull request by ajinkyan83**

### CODE REVIEW

**Review by lukaszgryglicki — CHANGES_REQUESTED** [review]
Just a question: did you tested all of this?
Adding any new metric requires changing at least 3 files (AFAIR).
elastic/service.go
affiliation/service.go
swagger.yaml

please just search for "gerrit" (no case sensitive) and check everywhere and then eventually check locally if that works, or let me know so I'll do this.
Thanks

**Comment by ajinkyan83** [comment]
> Just a question: did you tested all of this?
> Adding any new metric requires changing at least 3 files (AFAIR).
> elastic/service.go
> affiliation/service.go
> swagger.yaml
> 
> please just search for "gerrit" (no case sensitive) and check everywhere and then eventually check locally if that works, or let me know so I'll do this.
> Thanks

Thanks. I see that now, I had directly modified the swagger model file and so it worked locally.
Fixed now.

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
Please merge or let me know if I can merge so I'll check if that works.

**Comment by ajinkyan83** [comment]
> Please merge or let me know if I can merge so I'll check if that works.

Yes, please merge now.
Thanks.

**Pull request merged**
