### PR TITLE
more org cleanup

### PR DESCRIPTION
**Pull request by teragopher**

### CODE REVIEW

**Review by lukaszgryglicki — CHANGES_REQUESTED** [review]
I see soooo many changes - hard to review... can you sort this file? Say alphabetically by either `regexp` or the `mapping to` value, also remember that regexp is case insensitive (you probably did, but just in case)...

**Comment by teragopher** [comment]
@lukaszgryglicki Done

**Review by lukaszgryglicki — APPROVED** [review]
Thanks
/lgtm

**Comment by lukaszgryglicki** [comment]
Still some orgs are being deleted and recreated on each run, this is from 2nd run on the `test` - so it will repeat every time running on the `test` (26 circular orgs):
```
{"text":"Added organization 'Adobe' (id=45823), Deleted organization 'Adobe' (id=45823), Added organization 'Akamai Technologies' (id=45824), Deleted organization 'Akamai Technologies' (id=45824), Added organization 'AsiaInfo' (id=45825), Deleted organization 'AsiaInfo' (id=45825), Added organization 'BMC Software' (id=45826), Deleted organization 'BMC Software' (id=45826), Added organization 'Boston University' (id=45827), Added organization 'Cisco ' (id=45828), Deleted organization 'Cisco ' (id=45828), Added organization 'Dun & Bradstreet' (id=45829), Deleted organization 'Dun & Bradstreet' (id=45829), Deleted organization 'Electronic Arts Inc.' (id=45167), Added organization 'Electronic Arts Inc.' (id=45830), Added organization 'Extreme Networks' (id=45831), Deleted organization 'Extreme Networks' (id=45831), Added organization 'Facebook' (id=45832), Deleted organization 'Facebook' (id=45832), Added organization 'Fiserv' (id=45833), Deleted organization 'Fiserv' (id=45833), Deleted organization 'Google Inc' (id=45221), Deleted organization 'Google Summer of Code' (id=45222), Added organization 'Google Inc' (id=45834), Added organization 'Google Summer of Code' (id=45835), Added organization 'HP' (id=45836), Deleted organization 'HP' (id=45836), Added organization 'Infosys' (id=45837), Deleted organization 'Infosys' (id=45837), Added organization 'innoscale' (id=45838), Deleted organization 'innoscale' (id=45838), Added organization 'Intuit' (id=45839), Deleted organization 'Intuit' (id=45839), Deleted organization 'JPMorgan Chase & Co.' (id=45310), Added organization 'JPMorgan Chase & Co.' (id=45840), Added organization 'Mavenir' (id=45841), Deleted organization 'Mavenir' (id=45841), Updated organization name 'MediaMath, INC.' -> 'MediaMath, Inc.' (id=42429), Updated organization name 'MediaMath, Inc.' -> 'MediaMath, INC.' (id=42429), Added organization 'MSC Software' (id=45842), Deleted organization 'MSC Software' (id=45842), Added organization 'Nuance Communications' (id=45843), Deleted organization 'Nuance Communications' (id=45843), Added organization 'Playtech' (id=45844), Deleted organization 'Playtech' (id=45844), Added organization 'Riverbed Technology' (id=45845), Deleted organization 'Riverbed Technology' (id=45845), Added organization 'Sandvine' (id=45846), Deleted organization 'Sandvine' (id=45846), Deleted organization 'Boston University' (id=45827), Added organization 'Virtusa' (id=45847), Deleted organization 'Virtusa' (id=45847), Added organization 'Xilinx' (id=45848), Deleted organization 'Xilinx' (id=45848), Organizations: added:26 renamed:2 deleted:26 skipped:0, Enrollments: conflicts:0 updated:0"}
```
Ad this is 2nd run for `prod` (also 26 ciruclar orgs there):
```
{"text":"Added organization 'Adobe' (id=57494), Deleted organization 'Adobe' (id=57494), Added organization 'Akamai Technologies' (id=57495), Deleted organization 'Akamai Technologies' (id=57495), Added organization 'AsiaInfo' (id=57496), Deleted organization 'AsiaInfo' (id=57496), Added organization 'BMC Software' (id=57497), Deleted organization 'BMC Software' (id=57497), Added organization 'Boston University' (id=57498), Added organization 'Cisco ' (id=57499), Deleted organization 'Cisco ' (id=57499), Added organization 'Dun & Bradstreet' (id=57500), Deleted organization 'Dun & Bradstreet' (id=57500), Deleted organization 'Electronic Arts Inc.' (id=56841), Added organization 'Electronic Arts Inc.' (id=57501), Added organization 'Extreme Networks' (id=57502), Deleted organization 'Extreme Networks' (id=57502), Added organization 'Facebook' (id=57503), Deleted organization 'Facebook' (id=57503), Added organization 'Fiserv' (id=57504), Deleted organization 'Fiserv' (id=57504), Deleted organization 'Google Inc' (id=56895), Deleted organization 'Google Summer of Code' (id=56896), Added organization 'Google Inc' (id=57505), Added organization 'Google Summer of Code' (id=57506), Added organization 'HP' (id=57507), Deleted organization 'HP' (id=57507), Added organization 'Infosys' (id=57508), Deleted organization 'Infosys' (id=57508), Added organization 'innoscale' (id=57509), Deleted organization 'innoscale' (id=57509), Added organization 'Intuit' (id=57510), Deleted organization 'Intuit' (id=57510), Deleted organization 'JPMorgan Chase & Co.' (id=56983), Added organization 'JPMorgan Chase & Co.' (id=57511), Added organization 'Mavenir' (id=57512), Deleted organization 'Mavenir' (id=57512), Updated organization name 'MediaMath, INC.' -> 'MediaMath, Inc.' (id=53837), Updated organization name 'MediaMath, Inc.' -> 'MediaMath, INC.' (id=53837), Added organization 'MSC Software' (id=57513), Deleted organization 'MSC Software' (id=57513), Added organization 'Nuance Communications' (id=57514), Deleted organization 'Nuance Communications' (id=57514), Added organization 'Playtech' (id=57515), Deleted organization 'Playtech' (id=57515), Added organization 'Riverbed Technology' (id=57516), Deleted organization 'Riverbed Technology' (id=57516), Added organization 'Sandvine' (id=57517), Deleted organization 'Sandvine' (id=57517), Deleted organization 'Boston University' (id=57498), Added organization 'Virtusa' (id=57518), Deleted organization 'Virtusa' (id=57518), Added organization 'Xilinx' (id=57519), Deleted organization 'Xilinx' (id=57519), Organizations: added:26 renamed:2 deleted:26 skipped:0, Enrollments: conflicts:0 updated:0"}
```

**Pull request merged**
