### PR TITLE
[TEST] update map org names

### PR DESCRIPTION
**Pull request by bumblebee89**

### CODE REVIEW

**Comment by bumblebee89** [comment]
@lukaszgryglicki can you please take a look and when run please share any circular orgs if any. Thanks

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
Will run this tomorrow (if merged) and share the 1st run and 2nd run results (if there are circulars, they will show up in the 2nd run). Is this OK for you?

**Comment by bumblebee89** [comment]
@lukaszgryglicki perfect!!! Will merge it now and then tomorrow wait for the run results. Thank you

**Comment by lukaszgryglicki** [comment]
I'm getting:
```
{"Code":"500","Message":"PutMapOrgNames: QueryTX: Error 1139: Got error 'POSIX named classes are supported only within a class at offs...' from regexp"}
```
I guess some regexp is broken, trying to reproduce locally.

**Comment by lukaszgryglicki** [comment]
Managed to finally run locally (had broken Postgres after my CNCF test failure) - will try to figure out what is wrong there.

**Comment by lukaszgryglicki** [comment]
This is the exact error:
```
select id, name from organizations where name regexp '^[[:space:]]*d\\.\\?a.?[[:space:]]soft\\[[:space:]]inc.?[[:space:]]*$' and name != 'DA-SOFT Technologies';
``` 
It gives: `ERROR 1139 (42000): Got error 'POSIX named classes are supported only within a class at offset ' from regexp`.

Investigating.

**Comment by lukaszgryglicki** [comment]
I think the problem is `[[:space:]]soft\\[[:space:]]`, which should be `[[:space:]]soft[[:space:]]`

**Comment by lukaszgryglicki** [comment]
Another one here?
```
['^[[:space:]]*rohde[[:space:]]&[[:space:]]schwarz[[:space:]]gmbh[[:space:]]&[[:space:]]co\\.?[[:space:]]kg,?[[:space:]]de\\pt.?[[:space:]]1gs3[[:space:]]*$','Rohde & Schwarz GmbH & Co KG']
```
Should be
```
['^[[:space:]]*rohde[[:space:]]&[[:space:]]schwarz[[:space:]]gmbh[[:space:]]&[[:space:]]co\\.?[[:space:]]kg,?[[:space:]]dept\\.?[[:space:]]1gs3[[:space:]]*$','Rohde & Schwarz GmbH & Co KG']
```

**Comment by lukaszgryglicki** [comment]
Looks like those 2 are all errors, will build a new image, deploy and run on the `test` and let you know the results.

**Comment by bumblebee89** [comment]
Thanks @lukaszgryglicki

**Comment by lukaszgryglicki** [comment]
1st run:
```
{"text":"Added organization '1&1 Telecommunication SE' (id=76304), Deleted organization '1&1 Telecommunication SE' (id=76304), Deleted organization 'Adfinis SyGroup' (id=76189), Added organization 'Adfinis SyGroup' (id=76305), Added organization 'Amadeus' (id=76306), Deleted organization 'Amadeus' (id=76306), Added organization 'Arabian Internet and Communications Services Company Ltd' (id=76307), Deleted organization 'Arm Ltd' (id=76192), Added organization 'Arm Ltd' (id=76308), Added organization 'Aruba Networks, HPE' (id=76309), Deleted organization 'Aruba Networks, HPE' (id=76309), Updated organization name 'Athenahealth, Inc.' -> 'athenahealth, Inc.' (id=52622), Updated organization name 'athenahealth, Inc.' -> 'Athenahealth, Inc.' (id=52622), Deleted organization 'Fredhopper' (id=76226), Added organization 'Automatic Data Processing, Inc.' (id=76310), Deleted organization 'Automatic Data Processing, Inc.' (id=76310), Added organization 'Avanade' (id=76311), Deleted organization 'Avanade' (id=76311), Added organization 'Bloomberg' (id=76312), Deleted organization 'Bloomberg' (id=76312), Added organization 'Broadridge' (id=76313), Deleted organization 'Broadridge' (id=76313), Deleted organization 'Capital One Services Inc.' (id=76198), Added organization 'Capital One Services Inc.' (id=76314), Added organization 'CD Non LF Test LFPH' (id=76315), Added organization 'Char Software Inc' (id=76316), Added organization 'Cisco' (id=76317), Deleted organization 'Cisco' (id=76317), Added organization 'CloudChef' (id=76318), Updated organization 'CloudChef.tech' -> 'CloudChef' on 7 enrollments, Deleted organization 'CloudChef.tech' (id=76203), Added organization 'CloudChef.tech' (id=76319), Updated organization 'CloudChef' -> 'CloudChef.tech' on 7 enrollments, Deleted organization 'CloudChef' (id=76318), Added organization 'CloudCredo Limited' (id=76320), Added organization 'Comverse Technology, Inc.' (id=76321), Added organization 'Container Solutions' (id=76322), Deleted organization 'Container Solutions' (id=76322), Added organization 'Daimler' (id=76323), Deleted organization 'Daimler' (id=76323), Added organization 'Datto Inc' (id=76324), Deleted organization 'Datto Inc' (id=76324), Added organization 'DAVE Embedded Systems' (id=76325), Deleted organization 'DAVE Embedded Systems' (id=76325), Deleted organization 'Deloitte New Zealand' (id=76210), Added organization 'Deloitte New Zealand' (id=76326), Deleted organization 'devguard.io' (id=76211), Added organization 'devguard.io' (id=76327), Added organization 'Devoteam' (id=76328), Deleted organization 'Devoteam' (id=76328), Added organization 'Diebold Nixdorf' (id=76329), Deleted organization 'Diebold Nixdorf' (id=76329), Added organization 'Driver and Vehicle Licensing Agency' (id=76330), Deleted organization 'Driver and Vehicle Licensing Agency' (id=76330), Deleted organization 'e-Spirit AG' (id=76215), Added organization 'e-Spirit AG' (id=76331), Added organization 'eBay, Inc.' (id=76332), Added organization 'Econocom' (id=76333), Deleted organization 'Econocom' (id=76333), Added organization 'Egg breakers, egg centrifuges, egg washers - OVO-TECH' (id=76334), Added organization 'Equalibra' (id=76335), Updated organization 'Эквалибра' -> 'Equalibra' on 5 enrollments, Deleted organization 'Эквалибра' (id=76303), Added organization 'Ericsson' (id=76336), Deleted organization 'Ericsson' (id=76336), Added organization 'Fazlamesai' (id=76337), Updated organization 'fazlamesai.net' -> 'Fazlamesai' on 18 enrollments, Deleted organization 'fazlamesai.net' (id=76222), Added organization 'fazlamesai.net' (id=76338), Updated organization 'Fazlamesai' -> 'fazlamesai.net' on 18 enrollments, Deleted organization 'Fazlamesai' (id=76337), Added organization 'Fidelity National Information Services Inc' (id=76339), Added organization 'Fidelity National Information Services Inc.' (id=76340), Deleted organization 'Fidelity National Information Services Inc' (id=76339), Deleted organization 'Fidelity National Information Services Inc.' (id=76340), Added organization 'Fraunhofer-Gesellschaft' (id=76341), Deleted organization 'Fraunhofer-Gesellschaft' (id=76341), Added organization 'Fredhopper' (id=76342), Added organization 'Fujitsu' (id=76343), Deleted organization 'Fujitsu' (id=76343), Added organization 'General Services Administration' (id=76344), Added organization 'Google' (id=76345), Updated organization 'Google LLC' -> 'Google' on 18582 enrollments, Updated organization 'Google LLC' -> 'Google' on 25751 archived enrollments, Deleted organization 'Google LLC' (id=76230), Deleted organization 'Google Summer of Code' (id=76231), Added organization 'Google LLC' (id=76346), Updated organization 'Google' -> 'Google LLC' on 18582 enrollments, Updated organization 'Google' -> 'Google LLC' on 25751 archived enrollments, Deleted organization 'Google' (id=76345), Added organization 'Google Summer of Code' (id=76347), Deleted organization 'HEB' (id=76234), Added organization 'HashiCorp' (id=76348), Deleted organization 'HashiCorp' (id=76348), Added organization 'Hasura Technologies' (id=76349), Deleted organization 'Hasura Technologies' (id=76349), Added organization 'HEB' (id=76350), Deleted organization 'MapR Technologies' (id=76248), Deleted organization 'highstreet technologies GmbH' (id=76235), Added organization 'highstreet technologies GmbH' (id=76351), Added organization 'Hitachi Vantara' (id=76352), Deleted organization 'Hitachi Vantara' (id=76352), Added organization 'HP' (id=76353), Deleted organization 'HP' (id=76353), Added organization 'IIT Hyderabad' (id=76354), Deleted organization 'IIT Hyderabad' (id=76354), Deleted organization 'INFOR US INC' (id=76239), Added organization 'INFOR US INC' (id=76355), Added organization 'Infosys' (id=76356), Deleted organization 'Infosys' (id=76356), Added organization 'Innovating Tomorrow  LLC' (id=76357), Deleted organization 'Innovating Tomorrow  LLC' (id=76357), Added organization 'IOV Labs' (id=76358), Deleted organization 'IOV Labs' (id=76358), Deleted organization 'Ivannikov Institute for System Programming of the RAS' (id=76243), Added organization 'Ivannikov Institute for System Programming of the RAS' (id=76359), Added organization 'JFrog Inc.' (id=76360), Deleted organization 'JFrog Inc.' (id=76360), Deleted organization 'eBay, Inc.' (id=76332), Deleted organization 'CD Non LF Test LFPH' (id=76315), Added organization 'LinkedIn Corp.' (id=76362), Deleted organization 'LinkedIn Corp.' (id=76362), Deleted organization 'Lunar Bank A/S' (id=76246), Added organization 'Lunar Bank A/S' (id=76363), Added organization 'MaibornWolff' (id=76364), Deleted organization 'MaibornWolff' (id=76364), Added organization 'MapR Technologies' (id=76365), Deleted organization 'Comverse Technology, Inc.' (id=76321), Updated organization name 'MAXAR TECHNOLOGIES INC.' -> 'Maxar Technologies Inc.' (id=72349), Updated organization name 'Maxar Technologies Inc.' -> 'MAXAR TECHNOLOGIES INC.' (id=72349), Added organization 'MemSQL Inc.' (id=76366), Deleted organization 'MGM Resorts International Co.' (id=76250), Added organization 'MGM Resorts International Co.' (id=76367), Deleted organization 'Novell Japan Ltd' (id=76256), Added organization 'Minio' (id=76368), Deleted organization 'Minio' (id=76368), Added organization 'Ministère de la Défense' (id=76369), Updated organization 'Ministère des Armées' -> 'Ministère de la Défense' on 15 enrollments, Updated organization 'Ministère des Armées' -> 'Ministère de la Défense' on 1 archived enrollments, Deleted organization 'Ministère des Armées' (id=76253), Added organization 'Ministère des Armées' (id=76370), Updated organization 'Ministère de la Défense' -> 'Ministère des Armées' on 15 enrollments, Updated organization 'Ministère de la Défense' -> 'Ministère des Armées' on 1 archived enrollments, Deleted organization 'Ministère de la Défense' (id=76369), Deleted organization 'nbn™ Australia' (id=76254), Added organization 'nbn™ Australia' (id=76371), Added organization 'NCR Retail Solutions' (id=76372), Added organization 'Novell Japan Ltd' (id=76373), Added organization 'Open Source Automation Development Lab' (id=76374), Deleted organization 'Open Source Automation Development Lab' (id=76374), Added organization 'OutagePlanner' (id=76375), Updated organization 'OutagePlanner.com' -> 'OutagePlanner' on 6 enrollments, Deleted organization 'OutagePlanner.com' (id=76259), Added organization 'OutagePlanner.com' (id=76376), Updated organization 'OutagePlanner' -> 'OutagePlanner.com' on 6 enrollments, Deleted organization 'OutagePlanner' (id=76375), Deleted organization 'Egg breakers, egg centrifuges, egg washers - OVO-TECH' (id=76334), Updated organization name 'Pearson PLC' -> 'Pearson plc' (id=59475), Updated organization name 'Pearson plc' -> 'Pearson PLC' (id=59475), Added organization 'PEROOZ' (id=76377), Updated organization 'PEROOZ The Magazine Creator' -> 'PEROOZ' on 7 enrollments, Deleted organization 'PEROOZ The Magazine Creator' (id=76261), Added organization 'PEROOZ The Magazine Creator' (id=76378), Updated organization 'PEROOZ' -> 'PEROOZ The Magazine Creator' on 7 enrollments, Deleted organization 'PEROOZ' (id=76377), Deleted organization 'CloudCredo Limited' (id=76320), Deleted organization 'Points.com Inc' (id=76262), Added organization 'Points.com Inc' (id=76379), Deleted organization 'Praekelt.org' (id=76263), Added organization 'Praekelt.org' (id=76380), Added organization 'QNX Software Systems' (id=76381), Deleted organization 'QNX Software Systems' (id=76381), Added organization 'Qualcomm' (id=76382), Deleted organization 'Qualcomm' (id=76382), Added organization 'Red Hat' (id=76383), Deleted organization 'Red Hat' (id=76383), Added organization 'rock chips' (id=76384), Deleted organization 'rock chips' (id=76384), Added organization 'Rohde & Schwarz GmbH & Co KG' (id=76385), Updated organization 'Rohde & Schwarz GmbH & Co. KG, Dept. 1GS3' -> 'Rohde & Schwarz GmbH & Co KG' on 8 enrollments, Deleted organization 'Rohde & Schwarz GmbH & Co. KG, Dept. 1GS3' (id=76269), Added organization 'Rohde & Schwarz GmbH & Co. KG, Dept. 1GS3' (id=76386), Updated organization 'Rohde & Schwarz GmbH & Co KG' -> 'Rohde & Schwarz GmbH & Co. KG, Dept. 1GS3' on 8 enrollments, Deleted organization 'Rohde & Schwarz GmbH & Co KG' (id=76385), Added organization 'Salt' (id=76387), Deleted organization 'Salt' (id=76387), Added organization 'Scantrust' (id=76388), Deleted organization 'Scantrust' (id=76388), Added organization 'SEEDLAND' (id=76389), Deleted organization 'SEEDLAND' (id=76389), Added organization 'Shutterstock Inc' (id=76390), Updated organization 'Shutterstock, Inc.' -> 'Shutterstock Inc' on 9 enrollments, Updated organization 'Shutterstock, Inc.' -> 'Shutterstock Inc' on 13 archived enrollments, Deleted organization 'Shutterstock, Inc.' (id=76274), Added organization 'Shutterstock, Inc.' (id=76391), Updated organization 'Shutterstock Inc' -> 'Shutterstock, Inc.' on 9 enrollments, Updated organization 'Shutterstock Inc' -> 'Shutterstock, Inc.' on 13 archived enrollments, Deleted organization 'Shutterstock Inc' (id=76390), Deleted organization 'MemSQL Inc.' (id=76366), Added organization 'SmartBear Software Inc.' (id=76392), Deleted organization 'SmartBear Software Inc.' (id=76392), Added organization 'Snowflake Computing, Inc.' (id=76393), Deleted organization 'Snowflake Computing, Inc.' (id=76393), Deleted organization 'Snyk Ltd.' (id=76277), Added organization 'Snyk Ltd.' (id=76394), Added organization 'SoCal Blender' (id=76395), Updated organization 'SoCalBlender.org' -> 'SoCal Blender' on 8 enrollments, Deleted organization 'SoCalBlender.org' (id=76279), Added organization 'SoCalBlender.org' (id=76396), Updated organization 'SoCal Blender' -> 'SoCalBlender.org' on 8 enrollments, Deleted organization 'SoCal Blender' (id=76395), Deleted organization 'Arabian Internet and Communications Services Company Ltd' (id=76307), Deleted organization 'SoundCloud Inc' (id=76280), Added organization 'SoundCloud Inc' (id=76397), Added organization 'ST Microelectronics Srl' (id=76398), Deleted organization 'Wyoming' (id=76300), Deleted organization 'ST Microelectronics Srl' (id=76398), Deleted organization 'TED Foundation Inc' (id=76282), Added organization 'TED Foundation Inc' (id=76399), Added organization 'THE JOHNS HOPKINS UNIVERSITY APPLIED PHYSICS LABORATORY LLC' (id=76400), Deleted organization 'THE JOHNS HOPKINS UNIVERSITY APPLIED PHYSICS LABORATORY LLC' (id=76400), Deleted organization 'themachine.io' (id=76285), Added organization 'The Qt Company' (id=76401), Deleted organization 'The Qt Company' (id=76401), Added organization 'themachine.io' (id=76402), Added organization 'Tibco' (id=76403), Deleted organization 'Tibco' (id=76403), Added organization 'Trainline plc' (id=76404), Deleted organization 'Trainline plc' (id=76404), Added organization 'travel audience' (id=76405), Deleted organization 'travel audience' (id=76405), Added organization 'TV 2' (id=76406), Deleted organization 'TV 2' (id=76406), Added organization 'Twitch' (id=76407), Deleted organization 'Twitch' (id=76407), Added organization 'Uber' (id=76408), Deleted organization 'Uber' (id=76408), Deleted organization 'UBS Business Services AG' (id=76292), Added organization 'UBS Business Services AG' (id=76409), Added organization 'UCL' (id=76410), Deleted organization 'University of California, Los Angeles' (id=76296), Added organization 'UNC Charlotte' (id=76411), Added organization 'Universitat Politècnica de Catalunya' (id=76412), Deleted organization 'UCL' (id=76410), Added organization 'University of California, Los Angeles' (id=76413), Deleted organization 'UNC Charlotte' (id=76411), Deleted organization 'Universitat Politècnica de Catalunya' (id=76412), Deleted organization 'Char Software Inc' (id=76316), Deleted organization 'General Services Administration' (id=76344), Added organization 'Verisk' (id=76414), Deleted organization 'NCR Retail Solutions' (id=76372), Deleted organization 'Verisk' (id=76414), Deleted organization 'VSP Global' (id=76298), Added organization 'VSP Global' (id=76415), Deleted organization 'Wipro Tech' (id=76299), Added organization 'Wipro Tech' (id=76416), Added organization 'Wyoming' (id=76417), Deleted organization 'zbj.com' (id=76301), Added organization 'zbj.com' (id=76418), Deleted organization 'ZE PowerGroup Inc.' (id=76302), Added organization 'ZE PowerGroup Inc.' (id=76419), Added organization 'Эквалибра' (id=76420), Updated organization 'Equalibra' -> 'Эквалибра' on 5 enrollments, Deleted organization 'Equalibra' (id=76335), Organizations: added:116 renamed:6 deleted:116 skipped:0, Enrollments: conflicts:0 archive conflicts:0 updated:88860"}
```

**Comment by lukaszgryglicki** [comment]
Looks like it gives a lot of circular updates (116), see the 2nd run @bumblebee89 :
```
{"text":"Added organization '1&1 Telecommunication SE' (id=76421), Deleted organization '1&1 Telecommunication SE' (id=76421), Deleted organization 'Adfinis SyGroup' (id=76305), Added organization 'Adfinis SyGroup' (id=76422), Added organization 'Amadeus' (id=76423), Deleted organization 'Amadeus' (id=76423), Added organization 'Arabian Internet and Communications Services Company Ltd' (id=76424), Deleted organization 'Arm Ltd' (id=76308), Added organization 'Arm Ltd' (id=76425), Added organization 'Aruba Networks, HPE' (id=76426), Deleted organization 'Aruba Networks, HPE' (id=76426), Updated organization name 'Athenahealth, Inc.' -> 'athenahealth, Inc.' (id=52622), Updated organization name 'athenahealth, Inc.' -> 'Athenahealth, Inc.' (id=52622), Deleted organization 'Fredhopper' (id=76342), Added organization 'Automatic Data Processing, Inc.' (id=76427), Deleted organization 'Automatic Data Processing, Inc.' (id=76427), Added organization 'Avanade' (id=76428), Deleted organization 'Avanade' (id=76428), Added organization 'Bloomberg' (id=76429), Deleted organization 'Bloomberg' (id=76429), Added organization 'Broadridge' (id=76430), Deleted organization 'Broadridge' (id=76430), Deleted organization 'Capital One Services Inc.' (id=76314), Added organization 'Capital One Services Inc.' (id=76431), Added organization 'CD Non LF Test LFPH' (id=76432), Added organization 'Char Software Inc' (id=76433), Added organization 'Cisco' (id=76434), Deleted organization 'Cisco' (id=76434), Added organization 'CloudChef' (id=76435), Updated organization 'CloudChef.tech' -> 'CloudChef' on 7 enrollments, Deleted organization 'CloudChef.tech' (id=76319), Added organization 'CloudChef.tech' (id=76436), Updated organization 'CloudChef' -> 'CloudChef.tech' on 7 enrollments, Deleted organization 'CloudChef' (id=76435), Added organization 'CloudCredo Limited' (id=76437), Added organization 'Comverse Technology, Inc.' (id=76438), Added organization 'Container Solutions' (id=76439), Deleted organization 'Container Solutions' (id=76439), Added organization 'Daimler' (id=76440), Deleted organization 'Daimler' (id=76440), Added organization 'Datto Inc' (id=76441), Deleted organization 'Datto Inc' (id=76441), Added organization 'DAVE Embedded Systems' (id=76442), Deleted organization 'DAVE Embedded Systems' (id=76442), Deleted organization 'Deloitte New Zealand' (id=76326), Added organization 'Deloitte New Zealand' (id=76443), Deleted organization 'devguard.io' (id=76327), Added organization 'devguard.io' (id=76444), Added organization 'Devoteam' (id=76445), Deleted organization 'Devoteam' (id=76445), Added organization 'Diebold Nixdorf' (id=76446), Deleted organization 'Diebold Nixdorf' (id=76446), Added organization 'Driver and Vehicle Licensing Agency' (id=76447), Deleted organization 'Driver and Vehicle Licensing Agency' (id=76447), Deleted organization 'e-Spirit AG' (id=76331), Added organization 'e-Spirit AG' (id=76448), Added organization 'eBay, Inc.' (id=76449), Added organization 'Econocom' (id=76450), Deleted organization 'Econocom' (id=76450), Added organization 'Egg breakers, egg centrifuges, egg washers - OVO-TECH' (id=76451), Added organization 'Equalibra' (id=76452), Updated organization 'Эквалибра' -> 'Equalibra' on 5 enrollments, Deleted organization 'Эквалибра' (id=76420), Added organization 'Ericsson' (id=76453), Deleted organization 'Ericsson' (id=76453), Added organization 'Fazlamesai' (id=76454), Updated organization 'fazlamesai.net' -> 'Fazlamesai' on 18 enrollments, Deleted organization 'fazlamesai.net' (id=76338), Added organization 'fazlamesai.net' (id=76455), Updated organization 'Fazlamesai' -> 'fazlamesai.net' on 18 enrollments, Deleted organization 'Fazlamesai' (id=76454), Added organization 'Fidelity National Information Services Inc' (id=76456), Added organization 'Fidelity National Information Services Inc.' (id=76457), Deleted organization 'Fidelity National Information Services Inc' (id=76456), Deleted organization 'Fidelity National Information Services Inc.' (id=76457), Added organization 'Fraunhofer-Gesellschaft' (id=76458), Deleted organization 'Fraunhofer-Gesellschaft' (id=76458), Added organization 'Fredhopper' (id=76459), Added organization 'Fujitsu' (id=76460), Deleted organization 'Fujitsu' (id=76460), Added organization 'General Services Administration' (id=76461), Added organization 'Google' (id=76462), Updated organization 'Google LLC' -> 'Google' on 18582 enrollments, Updated organization 'Google LLC' -> 'Google' on 25751 archived enrollments, Deleted organization 'Google LLC' (id=76346), Deleted organization 'Google Summer of Code' (id=76347), Added organization 'Google LLC' (id=76463), Updated organization 'Google' -> 'Google LLC' on 18582 enrollments, Updated organization 'Google' -> 'Google LLC' on 25751 archived enrollments, Deleted organization 'Google' (id=76462), Added organization 'Google Summer of Code' (id=76464), Deleted organization 'HEB' (id=76350), Added organization 'HashiCorp' (id=76465), Deleted organization 'HashiCorp' (id=76465), Added organization 'Hasura Technologies' (id=76466), Deleted organization 'Hasura Technologies' (id=76466), Added organization 'HEB' (id=76467), Deleted organization 'MapR Technologies' (id=76365), Deleted organization 'highstreet technologies GmbH' (id=76351), Added organization 'highstreet technologies GmbH' (id=76468), Added organization 'Hitachi Vantara' (id=76469), Deleted organization 'Hitachi Vantara' (id=76469), Added organization 'HP' (id=76470), Deleted organization 'HP' (id=76470), Added organization 'IIT Hyderabad' (id=76471), Deleted organization 'IIT Hyderabad' (id=76471), Deleted organization 'INFOR US INC' (id=76355), Added organization 'INFOR US INC' (id=76472), Added organization 'Infosys' (id=76473), Deleted organization 'Infosys' (id=76473), Added organization 'Innovating Tomorrow  LLC' (id=76474), Deleted organization 'Innovating Tomorrow  LLC' (id=76474), Added organization 'IOV Labs' (id=76475), Deleted organization 'IOV Labs' (id=76475), Deleted organization 'Ivannikov Institute for System Programming of the RAS' (id=76359), Added organization 'Ivannikov Institute for System Programming of the RAS' (id=76476), Added organization 'JFrog Inc.' (id=76477), Deleted organization 'JFrog Inc.' (id=76477), Deleted organization 'eBay, Inc.' (id=76449), Deleted organization 'CD Non LF Test LFPH' (id=76432), Added organization 'LinkedIn Corp.' (id=76478), Deleted organization 'LinkedIn Corp.' (id=76478), Deleted organization 'Lunar Bank A/S' (id=76363), Added organization 'Lunar Bank A/S' (id=76479), Added organization 'MaibornWolff' (id=76480), Deleted organization 'MaibornWolff' (id=76480), Added organization 'MapR Technologies' (id=76481), Deleted organization 'Comverse Technology, Inc.' (id=76438), Updated organization name 'MAXAR TECHNOLOGIES INC.' -> 'Maxar Technologies Inc.' (id=72349), Updated organization name 'Maxar Technologies Inc.' -> 'MAXAR TECHNOLOGIES INC.' (id=72349), Added organization 'MemSQL Inc.' (id=76482), Deleted organization 'MGM Resorts International Co.' (id=76367), Added organization 'MGM Resorts International Co.' (id=76483), Deleted organization 'Novell Japan Ltd' (id=76373), Added organization 'Minio' (id=76484), Deleted organization 'Minio' (id=76484), Added organization 'Ministère de la Défense' (id=76485), Updated organization 'Ministère des Armées' -> 'Ministère de la Défense' on 15 enrollments, Updated organization 'Ministère des Armées' -> 'Ministère de la Défense' on 1 archived enrollments, Deleted organization 'Ministère des Armées' (id=76370), Added organization 'Ministère des Armées' (id=76486), Updated organization 'Ministère de la Défense' -> 'Ministère des Armées' on 15 enrollments, Updated organization 'Ministère de la Défense' -> 'Ministère des Armées' on 1 archived enrollments, Deleted organization 'Ministère de la Défense' (id=76485), Deleted organization 'nbn™ Australia' (id=76371), Added organization 'nbn™ Australia' (id=76487), Added organization 'NCR Retail Solutions' (id=76488), Added organization 'Novell Japan Ltd' (id=76489), Added organization 'Open Source Automation Development Lab' (id=76490), Deleted organization 'Open Source Automation Development Lab' (id=76490), Added organization 'OutagePlanner' (id=76491), Updated organization 'OutagePlanner.com' -> 'OutagePlanner' on 6 enrollments, Deleted organization 'OutagePlanner.com' (id=76376), Added organization 'OutagePlanner.com' (id=76492), Updated organization 'OutagePlanner' -> 'OutagePlanner.com' on 6 enrollments, Deleted organization 'OutagePlanner' (id=76491), Deleted organization 'Egg breakers, egg centrifuges, egg washers - OVO-TECH' (id=76451), Updated organization name 'Pearson PLC' -> 'Pearson plc' (id=59475), Updated organization name 'Pearson plc' -> 'Pearson PLC' (id=59475), Added organization 'PEROOZ' (id=76493), Updated organization 'PEROOZ The Magazine Creator' -> 'PEROOZ' on 7 enrollments, Deleted organization 'PEROOZ The Magazine Creator' (id=76378), Added organization 'PEROOZ The Magazine Creator' (id=76494), Updated organization 'PEROOZ' -> 'PEROOZ The Magazine Creator' on 7 enrollments, Deleted organization 'PEROOZ' (id=76493), Deleted organization 'CloudCredo Limited' (id=76437), Deleted organization 'Points.com Inc' (id=76379), Added organization 'Points.com Inc' (id=76495), Deleted organization 'Praekelt.org' (id=76380), Added organization 'Praekelt.org' (id=76496), Added organization 'QNX Software Systems' (id=76497), Deleted organization 'QNX Software Systems' (id=76497), Added organization 'Qualcomm' (id=76498), Deleted organization 'Qualcomm' (id=76498), Added organization 'Red Hat' (id=76499), Deleted organization 'Red Hat' (id=76499), Added organization 'rock chips' (id=76500), Deleted organization 'rock chips' (id=76500), Added organization 'Rohde & Schwarz GmbH & Co KG' (id=76501), Updated organization 'Rohde & Schwarz GmbH & Co. KG, Dept. 1GS3' -> 'Rohde & Schwarz GmbH & Co KG' on 8 enrollments, Deleted organization 'Rohde & Schwarz GmbH & Co. KG, Dept. 1GS3' (id=76386), Added organization 'Rohde & Schwarz GmbH & Co. KG, Dept. 1GS3' (id=76502), Updated organization 'Rohde & Schwarz GmbH & Co KG' -> 'Rohde & Schwarz GmbH & Co. KG, Dept. 1GS3' on 8 enrollments, Deleted organization 'Rohde & Schwarz GmbH & Co KG' (id=76501), Added organization 'Salt' (id=76503), Deleted organization 'Salt' (id=76503), Added organization 'Scantrust' (id=76504), Deleted organization 'Scantrust' (id=76504), Added organization 'SEEDLAND' (id=76505), Deleted organization 'SEEDLAND' (id=76505), Added organization 'Shutterstock Inc' (id=76506), Updated organization 'Shutterstock, Inc.' -> 'Shutterstock Inc' on 9 enrollments, Updated organization 'Shutterstock, Inc.' -> 'Shutterstock Inc' on 13 archived enrollments, Deleted organization 'Shutterstock, Inc.' (id=76391), Added organization 'Shutterstock, Inc.' (id=76507), Updated organization 'Shutterstock Inc' -> 'Shutterstock, Inc.' on 9 enrollments, Updated organization 'Shutterstock Inc' -> 'Shutterstock, Inc.' on 13 archived enrollments, Deleted organization 'Shutterstock Inc' (id=76506), Deleted organization 'MemSQL Inc.' (id=76482), Added organization 'SmartBear Software Inc.' (id=76508), Deleted organization 'SmartBear Software Inc.' (id=76508), Added organization 'Snowflake Computing, Inc.' (id=76509), Deleted organization 'Snowflake Computing, Inc.' (id=76509), Deleted organization 'Snyk Ltd.' (id=76394), Added organization 'Snyk Ltd.' (id=76510), Added organization 'SoCal Blender' (id=76511), Updated organization 'SoCalBlender.org' -> 'SoCal Blender' on 8 enrollments, Deleted organization 'SoCalBlender.org' (id=76396), Added organization 'SoCalBlender.org' (id=76512), Updated organization 'SoCal Blender' -> 'SoCalBlender.org' on 8 enrollments, Deleted organization 'SoCal Blender' (id=76511), Deleted organization 'Arabian Internet and Communications Services Company Ltd' (id=76424), Deleted organization 'SoundCloud Inc' (id=76397), Added organization 'SoundCloud Inc' (id=76513), Added organization 'ST Microelectronics Srl' (id=76514), Deleted organization 'Wyoming' (id=76417), Deleted organization 'ST Microelectronics Srl' (id=76514), Deleted organization 'TED Foundation Inc' (id=76399), Added organization 'TED Foundation Inc' (id=76515), Added organization 'THE JOHNS HOPKINS UNIVERSITY APPLIED PHYSICS LABORATORY LLC' (id=76516), Deleted organization 'THE JOHNS HOPKINS UNIVERSITY APPLIED PHYSICS LABORATORY LLC' (id=76516), Deleted organization 'themachine.io' (id=76402), Added organization 'The Qt Company' (id=76517), Deleted organization 'The Qt Company' (id=76517), Added organization 'themachine.io' (id=76518), Added organization 'Tibco' (id=76519), Deleted organization 'Tibco' (id=76519), Added organization 'Trainline plc' (id=76520), Deleted organization 'Trainline plc' (id=76520), Added organization 'travel audience' (id=76521), Deleted organization 'travel audience' (id=76521), Added organization 'TV 2' (id=76522), Deleted organization 'TV 2' (id=76522), Added organization 'Twitch' (id=76523), Deleted organization 'Twitch' (id=76523), Added organization 'Uber' (id=76524), Deleted organization 'Uber' (id=76524), Deleted organization 'UBS Business Services AG' (id=76409), Added organization 'UBS Business Services AG' (id=76525), Added organization 'UCL' (id=76526), Deleted organization 'University of California, Los Angeles' (id=76413), Added organization 'UNC Charlotte' (id=76527), Added organization 'Universitat Politècnica de Catalunya' (id=76528), Deleted organization 'UCL' (id=76526), Added organization 'University of California, Los Angeles' (id=76529), Deleted organization 'UNC Charlotte' (id=76527), Deleted organization 'Universitat Politècnica de Catalunya' (id=76528), Deleted organization 'Char Software Inc' (id=76433), Deleted organization 'General Services Administration' (id=76461), Added organization 'Verisk' (id=76530), Deleted organization 'NCR Retail Solutions' (id=76488), Deleted organization 'Verisk' (id=76530), Deleted organization 'VSP Global' (id=76415), Added organization 'VSP Global' (id=76531), Deleted organization 'Wipro Tech' (id=76416), Added organization 'Wipro Tech' (id=76532), Added organization 'Wyoming' (id=76533), Deleted organization 'zbj.com' (id=76418), Added organization 'zbj.com' (id=76534), Deleted organization 'ZE PowerGroup Inc.' (id=76419), Added organization 'ZE PowerGroup Inc.' (id=76535), Added organization 'Эквалибра' (id=76536), Updated organization 'Equalibra' -> 'Эквалибра' on 5 enrollments, Deleted organization 'Equalibra' (id=76452), Organizations: added:116 renamed:6 deleted:116 skipped:0, Enrollments: conflicts:0 archive conflicts:0 updated:88860"}
```

**Pull request merged**
