### PR TITLE
[TEST] update org map

### PR DESCRIPTION
**Pull request by bumblebee89**

### CODE REVIEW

**Review by lukaszgryglicki — APPROVED** [review]
/lgtm

**Comment by lukaszgryglicki** [comment]
OK for me but please resolve conflicts, merge and ping me - so I'll deploy and run for u.

**Comment by bumblebee89** [comment]
@lukaszgryglicki merged

**Comment by lukaszgryglicki** [comment]
Sorry, missed this, on it now...

**Comment by lukaszgryglicki** [comment]
1st run:
```
{"text":"Updated organization 'A+E Networks' -> 'A&E Television Networks, LLC' on 7 enrollments, Deleted organization 'A+E Networks' (id=45102), Updated organization 'A*STAR - Agency for Science, Technology and Research' -> 'A*Star - I2R' on 8 enrollments, Updated organization 'A*STAR - Agency for Science, Technology and Research' -> 'A*Star - I2R' on 1 archived enrollments, Deleted organization 'A*STAR - Agency for Science, Technology and Research' (id=50179), Updated organization 'Burner (Ad Hoc Labs)' -> 'Ad Hoc Labs, Inc.' on 6 enrollments, Updated organization 'Burner (Ad Hoc Labs)' -> 'Ad Hoc Labs, Inc.' on 2 archived enrollments, Deleted organization 'Burner (Ad Hoc Labs)' (id=43009), Updated organization 'Alibaba Group (China)' -> 'Alibaba Group' on 1 enrollments, Deleted organization 'Alibaba Group (China)' (id=50089), Updated organization 'Amdocs (Development Limited)' -> 'Amdocs Limited' on 666 enrollments, Updated organization 'Amdocs (Development Limited)' -> 'Amdocs Limited' on 384 archived enrollments, Deleted organization 'Amdocs (Development Limited)' (id=39293), Updated organization 'Asiainfo Technologies (China)  Inc.' -> 'AsiaInfo Technologies (China) Co., Ltd.' on 28 enrollments, Updated organization 'Asiainfo Technologies (China)  Inc.' -> 'AsiaInfo Technologies (China) Co., Ltd.' on 220 archived enrollments, Deleted organization 'Asiainfo Technologies (China)  Inc.' (id=58046), Updated organization 'Avenida+' -> 'Avenida Compras S.A.' on 5 enrollments, Deleted organization 'Avenida+' (id=45020), Updated organization '뱅크샐러드(레이니스트)' -> 'Banksalad Co., Ltd.' on 7 enrollments, Deleted organization '뱅크샐러드(레이니스트)' (id=42442), Updated organization 'Brocade Communications Systems Private Limited (India)' -> 'Broadcom Corporation' on 12 enrollments, Deleted organization 'Brocade Communications Systems Private Limited (India)' (id=53662), Updated organization 'Hyderabad (C-DAC)' -> 'Centre for Development of Advanced Computing' on 34 enrollments, Deleted organization 'Hyderabad (C-DAC)' (id=41584), Updated organization 'Hortonworks, Inc. ( acquired by Cloudera)' -> 'Cloudera, Inc.' on 33 enrollments, Updated organization 'Hortonworks, Inc. ( acquired by Cloudera)' -> 'Cloudera, Inc.' on 11 archived enrollments, Deleted organization 'Hortonworks, Inc. ( acquired by Cloudera)' (id=45746), Updated organization 'Communication Service for the Deaf (CSD)' -> 'Communication Service for the Deaf, Inc.' on 5 enrollments, Deleted organization 'Communication Service for the Deaf (CSD)' (id=39515), Updated organization 'Copyright Clearance Center (CCC)' -> 'Copyright Clearance Center Inc' on 7 enrollments, Updated organization 'Copyright Clearance Center (CCC)' -> 'Copyright Clearance Center Inc' on 1 archived enrollments, Deleted organization 'Copyright Clearance Center (CCC)' (id=35729), Updated organization 'DaoCloud (Shanghai DaoCloud Network Technology Co, LTD)' -> 'DaoCloud Network Technology Co., Ltd.' on 572 enrollments, Updated organization 'DaoCloud (Shanghai DaoCloud Network Technology Co, LTD)' -> 'DaoCloud Network Technology Co., Ltd.' on 2391 archived enrollments, Deleted organization 'DaoCloud (Shanghai DaoCloud Network Technology Co, LTD)' (id=50585), Updated organization 'Dell Corporation LTD.' -> 'Dell Technologies' on 683 enrollments, Updated organization 'Dell Corporation LTD.' -> 'Dell Technologies' on 2677 archived enrollments, Deleted organization 'Dell Corporation LTD.' (id=74802), Updated organization 'The Depository Trust & Clearing Corporation (DTCC)' -> 'Depository Trust and Clearing Corporation (DTCC)' on 43 enrollments, Updated organization 'The Depository Trust & Clearing Corporation (DTCC)' -> 'Depository Trust and Clearing Corporation (DTCC)' on 60 archived enrollments, Deleted organization 'The Depository Trust & Clearing Corporation (DTCC)' (id=36676), Updated organization 'Defence Electronics Application Laboratory (DEAL)' -> 'DRDO' on 8 enrollments, Updated organization 'Defence Electronics Application Laboratory (DEAL)' -> 'DRDO' on 12 archived enrollments, Deleted organization 'Defence Electronics Application Laboratory (DEAL)' (id=38532), Updated organization 'Electronics and Telecommunications Research Institute (ETRI)' -> 'Electronics and Telecommunications Research Institute' on 35 enrollments, Updated organization 'Electronics and Telecommunications Research Institute (ETRI)' -> 'Electronics and Telecommunications Research Institute' on 165 archived enrollments, Deleted organization 'Electronics and Telecommunications Research Institute (ETRI)' (id=50377), Updated organization 'Giesecke+Devrient' -> 'Giesecke + Devrient GmbH' on 9 enrollments, Deleted organization 'Giesecke+Devrient' (id=31082), Updated organization 'Gruner + Jahr' -> 'Gruner + Jahr GmbH' on 18 enrollments, Deleted organization 'Gruner + Jahr' (id=47361), Added organization 'Hortonworks, Inc. ( acquired by Cloudera)' (id=78073), Updated organization 'HUBER+SUHNER Polatis' -> 'HUBER+SUHNER' on 21 enrollments, Updated organization 'HUBER+SUHNER Polatis' -> 'HUBER+SUHNER' on 5 archived enrollments, Deleted organization 'HUBER+SUHNER Polatis' (id=27564), Updated organization 'KLM (Royal Dutch Airlines)' -> 'KLM Royal Dutch Airlines' on 8 enrollments, Updated organization 'KLM (Royal Dutch Airlines)' -> 'KLM Royal Dutch Airlines' on 32 archived enrollments, Deleted organization 'KLM (Royal Dutch Airlines)' (id=51893), Updated organization 'Leuze electronic GmbH + Co. KG' -> 'Leuze electronic GmbH & Co. KG' on 15 enrollments, Deleted organization 'Leuze electronic GmbH + Co. KG' (id=47209), Updated organization 'LF AI Foundation' -> 'LF AI & Data Foundation' on 16 enrollments, Updated organization 'LF AI Foundation' -> 'LF AI & Data Foundation' on 25 archived enrollments, Deleted organization 'LF AI Foundation' (id=36115), Updated organization 'Direction générale de l'armement (DGA)' -> 'Ministère des Armées' on 2 enrollments, Deleted organization 'Direction générale de l'armement (DGA)' (id=52789), Deleted organization 'Pearson Lanka (Pvt) Ltd' (id=75395), Updated organization 'ZeroTurnaround (Rogue Wave Software company)' -> 'Perforce Software Inc.' on 6 enrollments, Updated organization 'ZeroTurnaround (Rogue Wave Software company)' -> 'Perforce Software Inc.' on 5 archived enrollments, Deleted organization 'ZeroTurnaround (Rogue Wave Software company)' (id=46968), Updated organization 'PINGCAP (US), INC.' -> 'PingCAP' on 722 enrollments, Updated organization 'PINGCAP (US), INC.' -> 'PingCAP' on 2599 archived enrollments, Deleted organization 'PINGCAP (US), INC.' (id=74090), Updated organization 'Qbox (Supergiant)' -> 'Qbox, Inc.' on 24 enrollments, Updated organization 'Qbox (Supergiant)' -> 'Qbox, Inc.' on 39 archived enrollments, Deleted organization 'Qbox (Supergiant)' (id=51963), Updated organization 'UCloud Information Technology (HK) Limited' -> 'Shanghai UCloud Information Technology Co., Ltd.' on 75 enrollments, Updated organization 'UCloud Information Technology (HK) Limited' -> 'Shanghai UCloud Information Technology Co., Ltd.' on 141 archived enrollments, Deleted organization 'UCloud Information Technology (HK) Limited' (id=39388), Updated organization 'Software Assurance Marketplace (SWAMP)' -> 'Software Assurance Marketplace  (SWAMP)' on 6 enrollments, Deleted organization 'Software Assurance Marketplace (SWAMP)' (id=46229), Updated organization 'Springer Science + Business Media' -> 'Springer USA' on 11 enrollments, Deleted organization 'Springer Science + Business Media' (id=33558), Updated organization 'Styla GmbH (Styla.com)' -> 'Styla GmbH' on 6 enrollments, Deleted organization 'Styla GmbH (Styla.com)' (id=41598), Deleted organization 'TCL Corporate Research (Hong Kong) Co Limited' (id=75419), Updated organization 'Point Grey (Now FLIR Systems)' -> 'Teledyne FLIR LLC' on 8 enrollments, Updated organization 'Point Grey (Now FLIR Systems)' -> 'Teledyne FLIR LLC' on 4 archived enrollments, Deleted organization 'Point Grey (Now FLIR Systems)' (id=31313), Updated organization 'Evry AS (now TietoEVRY)' -> 'TietoEVRY' on 1 enrollments, Updated organization 'Evry AS (now TietoEVRY)' -> 'TietoEVRY' on 3 archived enrollments, Deleted organization 'Evry AS (now TietoEVRY)' (id=65115), Updated organization 'Trawel Audience' -> 'travel audience GmbH' on 17 enrollments, Updated organization 'Trawel Audience' -> 'travel audience GmbH' on 25 archived enrollments, Deleted organization 'Trawel Audience' (id=29847), Updated organization 'Turbonomic (fka VMTurbo)' -> 'Turbonomic, an IBM Company' on 7 enrollments, Deleted organization 'Turbonomic (fka VMTurbo)' (id=53895), Updated organization 'University of Agder (UiA)' -> 'Universitetet i Agder' on 5 enrollments, Updated organization 'University of Agder (UiA)' -> 'Universitetet i Agder' on 2 archived enrollments, Deleted organization 'University of Agder (UiA)' (id=49023), Updated organization 'University of Michigan - Advanced Research Computing (ARC)' -> 'University of Michigan' on 11 enrollments, Updated organization 'University of Michigan - Advanced Research Computing (ARC)' -> 'University of Michigan' on 9 archived enrollments, Deleted organization 'University of Michigan - Advanced Research Computing (ARC)' (id=48454), Updated organization 'Department of Defense (DoD)' -> 'US Department of Defense' on 1 enrollments, Deleted organization 'Department of Defense (DoD)' (id=58078), Updated organization 'Virtu Financia' -> 'Virtu Financial Inc.' on 14 enrollments, Deleted organization 'Virtu Financia' (id=57438), Updated organization 'Xevo (formerly UIEvolution)' -> 'Xevo Inc.' on 27 enrollments, Deleted organization 'Xevo (formerly UIEvolution)' (id=48322), Organizations: added:1 renamed:0 deleted:43 skipped:0, Enrollments: conflicts:0 archive conflicts:0 updated:12003"}
```

2nd run (1 circular org and also strange while space after `(` in name: `( acquired by Cloudera)`:
```
 {"text":"Deleted organization 'Hortonworks, Inc. ( acquired by Cloudera)' (id=78073), Added organization 'Hortonworks, Inc. ( acquired by Cloudera)' (id=78074), Organizations: added:1 renamed:0 deleted:1 skipped:0, Enrollments: conflicts:0 archive conflicts:0 updated:0"}
```
cc @bumblebee89

**Comment by bumblebee89** [comment]
@lukaszgryglicki got it... I will fix this and create a PR for prod.. Thanks :)

**Pull request merged**
